[tasks.deploy]
description = "Build release and install .so into local php"
command = "sudo"
args = ["cp", "target/release/libextensao_ds.so", "/usr/lib/php/20240924/"]
dependencies = ["build-release"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.stubs]
description = "Generate PHP IDE stub file from the extension source"
command = "cargo"
args = ["php", "stubs", "--out", "stubs/extensao_ds.stubs.php"]
dependencies = ["build-release"]